### ISSUE TITLE
Set "min" and "max" y values

### ISSUE THREAD

**Issue by jgmcelwain** [QingWei-Li/vue-trend#13] opened 2017-12-28 13:54 UTC
Would it be possible/within the scope of the project to add two new props, `min` and `max`, which would create static min and max Y values? I often have datasets which have a minimum value of 0 and a maximum value of 100, and being able to represent this by having the proportionate amount of space above/below the spark line would be really useful.

Example:

```
<trend
  :min="0"
  :max="100"
  :data="[15, 40, 92, 10]">
</trend>
```

**Comment by wopian** [comment] 2017-12-28 15:13
Duplicate of https://github.com/QingWei-Li/vue-trend/issues/8

**Closed** 2017-12-28 15:15 UTC
